package com.simon.basics.dao;

import com.simon.basics.model.Module;

public interface ModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    int deleteByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    int insert(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    int insertSelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    Module selectByPrimaryKey(Integer mid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    int updateByPrimaryKeySelective(Module record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    int updateByPrimaryKey(Module record);
}