package com.simon.basics.dao;

import com.simon.basics.model.ModuleRole;

public interface ModuleRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_role
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    int insert(ModuleRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_role
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    int insertSelective(ModuleRole record);
}