package com.simon.basics.dao;

import com.simon.basics.model.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    int insertSelective(UserRole record);
}