package com.simon.basics.model;

public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.mid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.mname
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    private String mname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.mid
     *
     * @return the value of module.mid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.mid
     *
     * @param mid the value for module.mid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.mname
     *
     * @return the value of module.mname
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.mname
     *
     * @param mname the value for module.mname
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }
}