package com.simon.basics.model;

public class ModuleRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_role.rid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_role.mid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    private Integer mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_role.rid
     *
     * @return the value of module_role.rid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_role.rid
     *
     * @param rid the value for module_role.rid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_role.mid
     *
     * @return the value of module_role.mid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_role.mid
     *
     * @param mid the value for module_role.mid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }
}