package com.simon.basics.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rname
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    private String rname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rid
     *
     * @return the value of role.rid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rid
     *
     * @param rid the value for role.rid
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rname
     *
     * @return the value of role.rname
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public String getRname() {
        return rname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rname
     *
     * @param rname the value for role.rname
     *
     * @mbggenerated Tue Sep 04 09:05:02 CST 2018
     */
    public void setRname(String rname) {
        this.rname = rname == null ? null : rname.trim();
    }
}